# Generated by Django 4.1.1 on 2022-09-09 09:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+12345678901",
                max_length=30,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
    ]
